before_script:
  - bundle update
script:
  - bundle exec cucumber
rvm:
  - ruby-head
  - 2.3.1
  - 2.2.4
  - 2.1
  - 2.0
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    on_success: always
    on_failure: always
