before_install:
  - gem install bundler
script:
  - bundle exec cucumber
rvm:
  - ruby-head
  - 2.3.1
  - 2.2.4
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    on_success: always
    on_failure: always
